<?php

$facts = [
    "Aleksandar Mitrović is a Serbian professional footballer who plays as a striker for Premier League club Fulham.",
    "He won the Serbian SuperLiga in his first season with .@FKPartizanBG, his boyhood club",
    "After dazzling at Partizan, he then joined .@rscanderlecht for a club record €5 million.",
    "Mitrović helped Serbia win the 2013 European Under-19 Championship, being voted the best player of the tournament.",
    "That same year 2013, he played his first game for the senior national team",
    "Aleksandar Mitrović is Serbia's highest goalscorer with 50 and counting.",
    "At .@rscanderlecht he scored 44 goals in 90 games across all competitions in his two-season spell at the club.",
    "He won the Belgian Pro League in his first campaign at .@rscanderlecht, and was the league's top scorer in his second.",
    "Mitrović won two different leagues in both of his debut seasons! How mad is that, talisman 🧿",
    "Mitro was loaned to .@FulhamFC in 2018, and the fans were delighted when he signed permanently after helping them achieve promotion to the prem.",
    "We love Mitro he is such a legend!",
    "It took Mitro only 9 mins to score his first .@ChampionsLeague goal, aged 18. On his official .@FKPartizanBG debut no less!",
    "By the end of his debut season, Mitrović was Partizan's top scorer in all competitions with 15 goals in 36 appearances even though he was one of the youngest players of the team.",
    "Did you know Mitro had a shift between the sticks? On 10 December 2013, in the last round of the .@ChampionsLeague Group stage against Olympiacos, Mitrović replaced goalkeeper Silvio Proto who had been sent off.",
    "On 5 November 2014, in the .@ChampionsLeague Group D game against Arsenal, he scored the equaliser in the 90th minute, completing .@rscanderlecht 's comeback from 3–0 to 3–3.",
    "On 21 July 2015, amid pletny of fanfare for the talented youngster, Mitrović joined Newcastle United .@NUFC on a five-year contract for a reported £13 million.",
    '"This is a club with a very big history and the fans are a big part of that. There will be pressure here, for sure, but I like pressure," said Mitrovic.',
    '"I also know about the famous players who have played for Newcastle United, like Alan Shearer, who is a hero of mine. I hope I can play like him for this club. It will be an honour."',
    "What do you think? How does Mitro measure up against Shearer at his best?",
    "Mitrovic was booked 22 seconds into his debut for .@NUFC - hard to find the stats but I make that one of the quickest bookings for a debut in the .@premierleague",
    "On 20 March 2016, Mitrovic headed the equaliser in a 1–1 draw against arch-rivals .@SunderlandAFC in the Tyne–Wear derby.",
    "On the final day of the 2016 season, with .@NUFC United already relegated, Mitro scored the second in a 5–1 win over 3rd-place .@SpursOfficial. He was also sent off for a shin-high challenge on Kyle Walker.",
    "He became only the sixth player in Premier League history to score a goal, assist a goal and get sent off in the same match.",
    "As a result, Mitrović had to wait until 13 September to make his .@SkyBetChamp debut, scoring his first goal of the 2016–17 season at Queens Park Rangers .@QPR",
    "Even towards the end of his time at .@NUFC, the fans continued to show their support for the striker. He described his recection in a 1-0 win over Palace as a 'still surprising heroes welcome'.",
    "On 1 February 2018, Mitrović joined (the mighty) .@FulhamFC on loan until the end of the season. The fans would clamour at the end of that season to make the move permanent.",
    "It wasn't a done deal - both Bordeaux and former club Anderlecht were after him. But supposedly fellow Serb .@Jokanovic, who was manager at the time, played a pivotal role in convincing the talented striker.",
    "Just a few years later, Aleksandar Mitrović is rightly seen as club legend.",
    "Only a matter of time until he has a statue 😅",
    "On 21 February, Mitrović scored his first goal for the club in a 1–1 draw with Bristol City. This kickstarted a run of form which saw him score six goals in four matches.",
    "In the six matches played by Fulham in April, Mitrović scored five times, including winning goals against Sheffield Wednesday .@swfc and .@SunderlandAFC",
    "Due to his prolific run of form in March and April 2018, he was the back-to-back .@SkyBetChamp Player of the Month.",
    "The goal against .@SunderlandAFC would prove to be his last for the club in his loan spell, as he did not score in the play-offs, but he did start in the play-off final, with Fulham beating Aston Villa 1–0.",
    "As a personal aside, that play-off final against Villa was one of my fave days of football ever; sun shining and fans singing. Bliss.",
    "On 30 July, Mitrović signed for Fulham permanently for an initial fee of £22 million, potentially rising to £27 million. Bargain.",
    "Mitrović scored four goals in his first three games of the 2018/19 season, which contributed to his total of 11, beating his previous prem scoring record of 9.",
    "Unfortunately that total was not ultimately able to keep FFC up, and they were relagated in the summer of 2019.",
    "Mitrović began the next season in great form, scoring five goals in six matches.",
    "In October, he went on another scoring run with six goals in five matches, including a hat-trick against Luton Town.",
    "He kept scoring throughout November and December, but got injured for a few weeks in January 2020. No worries though, he returned on 1 February against Huddersfield and scored @FulhamFC 's third goal in a 3–2 home win.",
    "He was unfortunatelty injured in January, but his return in February saw another scoring run during the month, culminating with a stoppage-time winner over Swansea City",
    "Then covid happened, as you know, so there was that break.",
    "On 10 July, Mitrović returned to the team, winning and converting a penalty in a 2–0 win over Cardiff City.",
    "On 18 July, Mitrović scored twice and assisted for .@bobbyreid93 (another legend), in a 5–3 win over Sheffield Wednesday, to keep Fulham's slim hopes of automatic promotion alive.",
    "Mitrović finished the season with twenty-six goals, winning the Golden Boot.",
    "He played a huge part in the 2019/20 play-off final, providing the assist for Joe Bryan's second goal in Fulham's extra-time win over Brentford. Could there be any better opponent to sink in extra time??",
    "Mitrović was named the 2019/20 Player of the Season by the club's supporters. Hero.",
    "Unfortunately 2020/21 season was not kind to Mitro. But to be fair it wasnt great for #ffc either. Mitro didn't score for over six months; partly due to injury, but also poor management by Parker",
    "Wikipedia says that Mitro was kept out the side by tactical changes, citing Lookman and Cav as playing better. Nonsense. It was that bore Parker that chose to bench him - and has subsequently been shown to be wrong.",
    "Following Fulham's return to the Championship, Mitrović was reinstated into the starting line-up by new manager Marco Silva. Real recognise real!",
    "In August 2021, he scored four goals in four consecutive matches. Lazy journos started trotting out the cliche 'too good for the champs, not good enough for the prem'. Lets just wait and see about that hey 😏",
    "On 29 September 2021, Mitrović scored his first hat-trick of the season, in a 3–1 home win over Swansea City, with all three goals coming in the first half of the game. At the races.",
    "His strong start to the season continued into October as he scored eight goals, including another hat-trick, this time against West Bromwich Albion. He was awarded the .@SkyBetChamp Player of the Month award for his efforts.",
    "Mitrović scored his third hat-trick of the season in an emphatic 6–2 home win over Bristol City on 15 January 2022, taking his goal tally to 27 league goals in just 24 games. Man said point to prove!",
    "On 12 February 22, Mitrović scored his 31st goal of the season with the only goal in a victory over Hull City, equalling the record for the most goals in a Championship season set by Ivan Toney the previous year with 16 matches still to play. No messing about!",
    "He broke this record nine days later, scoring his 32nd and 33rd goals of the season in a 2-1 home win over Peterborough United. No time to lose.",
    "On 19 April 2022, Mitrović scored his 39th and 40th league goals of the campaign in a 3–0 home win over Preston North End. The result confirmed Fulham's promotion back to the Premier League. Can I a get a 🥳",
    "On 24 April, Mitrović was voted .@SkyBetChamp Player of the Season at the annual EFL Awards. Naturally.",
    "He was also named in the Team of the Season, alongside Fulham teammates .@TosinAdarabioyo, .@Antonee_Jedi and .@harrywilson_. Effin legends.",
    "In a 7–0 win against Luton Town on 2 May, Mitrović scored two goals to equal and then break the record of Guy Whittingham for the highest scoring English league season in the current 46 game format by scoring 43 goals in a season. League lenged status confirmed.",
    "The win also confirmed Fulham as the Championship winners.",
    "That 7-0 win was honestly one of the best ever days to be a .@FulhamFC fan - Luton were still playing for the playoff spot, but #ffc decided to put on a show. I wear my scarf league winners scarf regularly 😅",
    "On the news of .@FulhamFC's promotion, those lazy journos started dribbling doubt about the clubs chances for the 22/23 season. 'Yo-yo club' they would spout. Tbf, fans were nervous. Two consecutive up-downs was tiring.",
    "On 6 August 2022, in Fulham's first match of the 2022–23 Premier League season, Mitrović scored both goals in a 2–2 home draw against Liverpool. On the way, we were saying we would take a 4 - 0 loss lmao.",
    "Mitro was majestic that day, one of his best ever performances. At one point he set off alone against the Liv defense, def not his usual game. Expecting him to lose the race, he Cruyffed and left Virgil in another timezone.",
    "Mitrović scored a 90th minute winner in a 3–2 home win over Brentford on 20 August. As previously mentioned, no better opponent to bag a last minute winner against.",
    "Mitrović scored his fifth goal of the season in a 2–1 home win over Brighton & Hove Albion, and four days later scored his sixth goal in six Premier League games in a 2–1 away defeat at Tottenham Hotspur.",
    "He scored in a 2–1 defeat to Arsenal on 27 August, which was his 100th goal for .@FulhamFC while also beating his goal tally from the entire 2020–21 season in just four games. Lazy journos starting to be exposed.",
    "Mitrović scored his fifth goal of the season in a 2–1 home win over Brighton, and four days later scored his sixth goal in six Premier League games in a 2–1 away defeat at Tottenham Hotspur.",
    "Mitrović returned to the Fulham team after missing one game; a 3–1 away loss at West Ham United Basketball Club",
    "He went on to score in the next three consecutive games against Bournmouth, Villa and Leeds.",
    "Following the World Cup break, Mitrović has continued his fine goalscoring form, scoring in a 3–0 away win at Crystal Palace",
    "He was unfortunate to miss a 96th minute penalty in a 2–1 win over Southampton. It was no surprise, however, that the fans instantly chanted his name after the miss.",
    "He ended 2022 scoring 31 goals in 35 games across the EFL Championship and Premier League",
    "Never keen to stop, he has kicked off 2023 in Mitro style, scoring the only goal in a away win at Leicester. This secured Fulham's third consecutive Premier League win for the first time since 2009",
    "I'm out of facts for now. I try to keep this updated as much as possible, but bear with me if am slow. If you have anything you want included or want to get involved, let me know!",

];
