<?php

$facts = [
    "Aleksandar Mitrović is a Serbian professional footballer who plays as a striker for Premier League club Fulham and the England.",
    "He won the Serbian SuperLiga in his first season with .@FKPartizanBG, his boyhood club",
    "After dazzling at Partizan, he then joined .@rscanderlecht for a club record €5 million.",
    "Mitrović helped Serbia win the 2013 European Under-19 Championship, being voted the best player of the tournament.",
    "That same year 2013, he played his first game for the senior national team",
    "Aleksandar Mitrović is Serbia's highest goalscorer with 50 and counting.",
    "At .@rscanderlecht he scored 44 goals in 90 games across all competitions in his two-season spell at the club.",
    "He won the Belgian Pro League in his first campaign at .@rscanderlecht, and was the league's top scorer in his second.",
    "Mitrović won two different leagues in both of his debut seasons! How mad is that, talisman 🧿",
    "In 2015, Mitro moved to .@NUFC United for £13 million, amid pletny of fanfare for the talented youngster.",
    "It was a shame for Aleksander that this move did not work out as he was, and remains, a .@NUFC fan",
    "Mitro was loaned to .@FulhamFC in 2018, and the fans were delighted when he signed permanently after helping them achieve promotion to the prem.",
    "We love Mitro he is such a legend!",
    "It took Mitro only 9 mins to score his first .@ChampionsLeague goal, aged 18. On his official .@FKPartizanBG debut no less!",
    "By the end of his debut season, Mitrović was Partizan's top scorer in all competitions with 15 goals in 36 appearances even though he was one of the youngest players of the team.",
    "Did you know Mitro had a shift between the sticks? On 10 December 2013, in the last round of the .@ChampionsLeague Group stage against Olympiacos, Mitrović replaced goalkeeper Silvio Proto who had been sent off.",
    "On 5 November 2014, in the .@ChampionsLeague Group D game against Arsenal, he scored the equaliser in the 90th minute, completing .@rscanderlecht 's comeback from 3–0 to 3–3.",
    "On 21 July 2015, Mitrović joined Newcastle United .@NUFC on a five-year contract for a reported £13 million.",
    '"This is a club with a very big history and the fans are a big part of that. There will be pressure here, for sure, but I like pressure," said Mitrovic.',
    '"I also know about the famous players who have played for Newcastle United, like Alan Shearer, who is a hero of mine. I hope I can play like him for this club. It will be an honour."',
    "What do you think? How does Mitro measure up against Shearer at his best?",
    "Mitrovic was booked 22 seconds into his debut for .@NUFC - hard to find the stats but I make that one of the quickest bookings for a debut in the .@premierleague",
    "On 20 March 2016, Mitrovic headed the equaliser in a 1–1 draw against arch-rivals .@SunderlandAFC in the Tyne–Wear derby.",
    "On the final day of the 2016 season, with .@NUFC United already relegated, Mitro scored the second in a 5–1 win over 3rd-place .@SpursOfficial. He was also sent off for a shin-high challenge on Kyle Walker.",
    "He became only the sixth player in Premier League history to score a goal, assist a goal and get sent off in the same match.",
    "As a result, Mitrović had to wait until 13 September to make his .@SkyBetChamp debut, scoring his first goal of the 2016–17 season at Queens Park Rangers .@QPR",
    "Even towards the end of his time at .@NUFC, the fans continued to show their support for the striker. He described his recection in a 1-0 win over Palace as a 'still surprising heroes welcome'.",
    "On 1 February 2018, Mitrović joined (the mighty) .@FulhamFC on loan until the end of the season. The fans would clamour at the end of that season to make the move permanent.",
    "It wasn't a done deal - both Bordeaux and former club Anderlecht were after him. But supposedly fellow Serb .@Jokanovic, who was manager at the time, played a pivotal role in convincing the talented striker.",
    "Just a few years later, Aleksandar Mitrović is rightly seen as club legend.",
    "Only a matter of time until he has a statue 😅",
    "On 21 February, Mitrović scored his first goal for the club in a 1–1 draw with Bristol City. This kickstarted a run of form which saw him score six goals in four matches.",
    "In the six matches played by Fulham in April, Mitrović scored five times, including winning goals against Sheffield Wednesday .@swfc and .@SunderlandAFC",
    "Due to his prolific run of form in March and April 2018, he was the back-to-back .@SkyBetChamp Player of the Month.",
    "The goal against .@SunderlandAFC would prove to be his last for the club in his loan spell, as he did not score in the play-offs, but he did start in the play-off final, with Fulham beating Aston Villa 1–0.",
    "As a personal aside, that play-off final against Villa was one of my best days of football ever; sun shining and fans singing. Bliss.",
    "On 30 July, Mitrović signed for Fulham permanently for an initial fee of £22 million, potentially rising to £27 million. Bargain.",
    "Mitrović scored four goals in his first three games of the 2018/19 season, which contributed to his total of 11, beating his previous prem scoring record of 9.",
    "Unfortunately that total was not ultimately able to keep FFC up, and they were relagated in the summer of 2019.",
    "Mitrović began the next season in great form, scoring five goals in six matches.",
    "In October, he went on another scoring run with six goals in five matches, including a hat-trick against Luton Town.",
    "He kept scoring throughout November and December, but got injured for a few weeks in January 2020. No worries though, he returned on 1 February against Huddersfield and scored @FulhamFC 's third goal in a 3–2 home win.",
    " another scoring run during the month, culminating with a stoppage-time winner over Swansea City",
    "Then covid happened, as you know, so there was that break.",
    "On 10 July, Mitrović returned to the team, winning and converting a penalty in a 2–0 win over Cardiff City.",
    "On 18 July, Mitrović scored twice and assisted for .@bobbyreid93 (another legend), in a 5–3 win over Sheffield Wednesday, to keep Fulham's slim hopes of automatic promotion alive.",
    "Mitrović finished the season with twenty-six goals, winning the Golden Boot.",
    "He played a huge part in the 2019/20 play-off final, providing the assist for Joe Bryan's second goal in Fulham's extra-time win over Brentford. Could there be any better opponent to sink in extra time??",  
    "Mitrović was named the 2019/20 Player of the Season by the club's supporters. Hero.",
    "Unfortunately 2020/21 season was not kind to Mitro. But to be fair it wasnt great for #ffc either. Mitro would go on a goal droubt that lasted over six months. 😥",
    "Wikipedia says that Mitro was kept out the side by tactical changes, siting Lookman and Cav as playing better. Nonsense. It was that bore Parker that chose to bench him - and at time of writing in 2022, it's now evident that Parker has inferior tactical decision-making.",
    "",
    "I'm out of facts 😅 for now anyway. I've got a bunch more to add. But if you have anything you want included let me know below!"
];
