name: tweetliker

on:
  push
  # schedule:
  #   - cron: "0,30 * * * *"

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}



  likingtweets:
    runs-on: ubuntu-latest
    environment: Tweetliker
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1.10
      - run: echo "Value of MY_SECRET1: $MY_SECRET1"
        env:
          MY_SECRET1: ${{ secrets.MY_SECRET1 }}
      - name: search and like tweets
        run: php tweetliker.php
