name: tweetliker

on:
  push
  # schedule:
  #   - cron: "0,30 * * * *"

jobs:
  likingtweets:
    runs-on: ubuntu-latest
    environment: Tweetliker
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1.10
      - name: search and like tweets
        run: php tweetliker.php
